CREATE SCHEMA IF NOT EXISTS coffee_machine

CREATE TABLE IF NOT EXISTS coffee_machine.t_coffee (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name_type VARCHAR(128) NOT NULL UNIQUE,
    ingredients TEXT NOT NULL,
    instructions TEXT NOT NULL,
    prep_time timestamp NOT NULL,
    calories INT
)