CREATE TABLE IF NOT EXISTS  coffee_machine.ingredients
(
    id  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    count INT DEFAULT 0
);

CREATE TABLE IF NOT EXISTS coffee_machine.recipe (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    c_name VARCHAR(255) NOT NULL UNIQUE,
    quantity_buyers INT DEFAULT 0,
    coffee_id INT REFERENCES coffee_machine.t_coffee(id)
);

CREATE TABLE IF NOT EXISTS coffee_machine.recipe_ingredients (
    ingredient_id INT REFERENCES coffee_machine.ingredients(id),
    recipe_id INT REFERENCES coffee_machine.recipe(id),
    PRIMARY KEY (recipe_id, ingredient_id)
)

