CREATE TABLE coffee_machine.ingredients
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL
);

CREATE TABLE coffee_machine.recipe_ingredients
(
    recipe_id     BIGINT,
    ingredient_id BIGINT,
    quantity      VARCHAR(50),
    buyers_count BIGINT DEFAULT 0,
    PRIMARY KEY (recipe_id, ingredient_id),
    FOREIGN KEY (recipe_id) REFERENCES t_coffee (id),
    FOREIGN KEY (ingredient_id) REFERENCES ingredients (id)
);